services:
  - type: web
    name: Snitch
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
